# Starter pipeline-For testing purpose
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello New, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See [![Build Status](https://dev.azure.com/akhilesh0274/New%20Test%20I2k2/_apis/build/status/akhileshnigam.Janta?branchName=master)](https://dev.azure.com/akhilesh0274/New%20Test%20I2k2/_build/latest?definitionId=1&branchName=master)
  displayName: 'Run a multi-line script'
